---
#      _ _           _                                   ___            _        
#   __| (_) __ _  __| | __ _  __ _       ___ _ __ ___   / / |_ __ _ ___| | _____ 
#  / _` | |/ _` |/ _` |/ _` |/ _` |_____/ __| '__/ __| / /| __/ _` / __| |/ / __|
# | (_| | | (_| | (_| | (_| | (_| |_____\__ \ | | (__ / / | || (_| \__ \   <\__ \
#  \__,_|_|\__, |\__,_|\__,_|\__, |     |___/_|  \___/_/   \__\__,_|___/_|\_\___/
#          |___/             |___/                                               
# install-src
# -----------------------------------------------------------------------------
- name: install-src | digdag should be installed
  get_url:
    url:   "https://dl.digdag.io/digdag-latest"
    dest:  "{{ digdag.dest }}/digdag"
    owner: "{{ digdag.user.username }}"
    group: "{{ digdag.user.group }}"
    mode:  "0755"

