---
#      _ _           _                                   ___            _        
#   __| (_) __ _  __| | __ _  __ _       ___ _ __ ___   / / |_ __ _ ___| | _____ 
#  / _` | |/ _` |/ _` |/ _` |/ _` |_____/ __| '__/ __| / /| __/ _` / __| |/ / __|
# | (_| | | (_| | (_| | (_| | (_| |_____\__ \ | | (__ / / | || (_| \__ \   <\__ \
#  \__,_|_|\__, |\__,_|\__,_|\__, |     |___/_|  \___/_/   \__\__,_|___/_|\_\___/
#          |___/             |___/                                               
# tasks file for ar-digdag-src
- include: create-user.yml
- include: install-pkg.yml
- include: install-src.yml
- include: make-config.yml
- include: build-local.yml
- include: boot-script.yml

